### PR TITLE
Shared GitHub workflows

### PR DESCRIPTION
**Pull request by djbe**
Updates this template with most changes applied in other repositories (bermbeeld, wilms, evck, …).

- Update dockerfile & use docker ignore to our advantage
- Use shared workflows for deployment & pr checks
- Added a docker compose file to mirror the testing environment on CI

### CODE REVIEW

**Comment by djbe** [comment]
Seems like the tests are broken, seems like they're all getting cancelled or stopping too early?
> failureType: 'cancelledByParent',
> cause: 'Promise resolution is still pending but the event loop has already resolved'

**Comment by djbe** [comment]
Ah great, the tests pass now 🎉 

I took a quick glance at the logs, there seems to be this error/warning though? Might be worth going through them carefully:
> # QueryFailedError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"

**Review by SebastiaanVanspauwen — APPROVED** [review]

**Comment by SebastiaanVanspauwen** [comment]
Hmm yeah interesting, seems like it is due to typeorm generating multiple tables at once for some reason
`... typeorm creates two tables in the same time, and I receive the error pg_type_typname_nsp_index`
https://github.com/typeorm/typeorm/issues/6125

**Comment by djbe** [comment]
So no real resolution then… We want to run the tests in parallel, stuff is slow enough as is in larger projects. 

It doesn't seem to break the tests though, so I think we're good?

**Comment by SebastiaanVanspauwen** [comment]
Yeah, this seems fine 👍

**Review by jorenvandeweyer — APPROVED** [review]

**Comment by jorenvandeweyer** [comment]
Nice thanks!

NestJS seems to be able to handle reconnecting automatically 🤷

**Pull request merged**
